### ISSUE TITLE
Encryption Question with S3 Logging

### ISSUE THREAD

**Issue by ghost** [eleven41/aws-lambda-encrypt-s3-objects#1]
Hello, I have not tried out your script but was curious that if you use this function to encryption logs generated by S3, does the lambda function generate more S3 logs that have to subsequently be encrypted.  Basically, does this perpetually generate traffic that has to constantly be encrypted?

Thanks!

**Comment by mwhouser** [comment]
This scenario has not been tested, but I believe it would create perpetual traffic.

**Comment by mwhouser** [comment]
However, that that may only be true if you had logging enabled on the logging target bucket itself, which could create it's own perpetual traffic.

If the bucket of logs does not have logging enabled, then it should not generate more traffic.
