### ISSUE TITLE
Getting Object Head error

### ISSUE THREAD

**Issue by CaseyLabs** [eleven41/aws-lambda-encrypt-s3-objects#4]
Hi there,

Really interested in using this function, but ran into the following error messages when deploying it.

I've granted full S3 access to the IAM role, just to ensure it's not a policy problem. No luck though. Any ideas?

Thanks!

2017-03-03T22:05:39.858Z	6597b97d-005d-11e7-a9fd-8fcdc456fbd0	Getting object head
2017-03-03T22:05:39.932Z	6597b97d-005d-11e7-a9fd-8fcdc456fbd0	Error getting object head:
2017-03-03T22:05:39.932Z	6597b97d-005d-11e7-a9fd-8fcdc456fbd0	{ [Forbidden: null]
message: null,
code: 'Forbidden',
region: null,
time: Fri Mar 03 2017 22:05:39 GMT+0000 (UTC),
requestId: 'XXXXXXXXXXXX',
extendedRequestId: 'XXXXXXXXXX',
cfId: undefined,
statusCode: 403,
retryable: false,
retryDelay: 17.542093549855053 } 'Forbidden: null\n at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:518:35)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)\n at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'

**Comment by mwhouser** [comment]
The `Forbidden` error basically means you don't have permission to access the object.

So either the Lambda function does not have the permissions to execute the command, or perhaps the bucket has a bucket policy attached that's prohibiting access.

**Comment by CaseyLabs** [comment]
Bingo: the owner of the objects within the S3 bucket were set to a different account. Thanks again for this script!
